baseURL: https://travismarceau.netlify.com/
languageCode: en-us
title: My New Hugo Site
theme: yourfolio
copyright: Copyright © 2019 - Travis Marceau. All Rights Reserved.

paginate: 3
googleAnalytics: YourGoogleAnalyticsID

# Menu Items
menu:
  global:
    - name: About
      url: /
    - name: Blog
      url: /post/
    - name: Contact
      url: /contact/

params:
  description: Your site description
  author: Travis Marceau
  logoImage: /img/travismarceau_logo.png
  logoImageAlt: travismarceau

taxonomies:
  category: categories
  tag: tags

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml