baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "yourfolio"
copyright = "Copyright © 2019 - Travis Marceau. All Rights Reserved."

paginate = 3
googleAnalytics = "Yout Google Analytics ID"

[[menu.global]]
    name = "About"
    url = "/"

[[menu.global]]
    name = "Blog"
    url = "/post/"

[[menu.global]]
    name = "Contact"
    url = "/contact/"

[params]
  description = "Your site description"
  author = "Your Name"
  logo = '/image/logo.png'

[taxonomies]
  category = "categories"
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"